Add release workflow
boa-dev/ryu-js pull request #45
Opened 2024-03-02 17:06 UTC by HalidOdat

This add a release workflow (pretty much a copy of boa's workflow), this should make it easier for use to publish new releases.

I will add the needed secret for this to work.

2024-03-02 18:24 UTC, jedel1043 requested changes

2024-03-02 18:24 UTC, jedel1043 commented on .github/workflows/release.yml
> +            skip
I would suggest copying `temporal_rs` for this, because single crates can avoid using `cargo workspace` for pubilshing.

2024-03-02 20:39 UTC, jedel1043 approved these changes

2024-03-03 18:23 UTC, raskad approved these changes

2024-03-03 18:28 UTC, merged